export const ALL_SONGS_REQUEST = 'ALL_SONGS_REQUEST'
export const ALL_SONGS_SUCCESS = 'ALL_SONGS_SUCCESS'
export const ALL_SONGS_FAIL = 'ALL_SONGS_FAIL'

export const DETAILS_SONG_REQUEST = 'DETAILS_SONG_REQUEST'
export const DETAILS_SONG_SUCCESS = 'DETAILS_SONG_SUCCESS'
export const DETAILS_SONG_FAIL = 'DETAILS_SONG_FAIL'

export const NEW_SONG_REQUEST = 'NEW_SONG_REQUEST'
export const NEW_SONG_SUCCESS = 'NEW_SONG_SUCCESS'
export const NEW_SONG_FAIL = 'NEW_SONG_FAIL'

export const EDIT_SONG_REQUEST = 'EDIT_SONG_REQUEST'
export const EDIT_SONG_SUCCESS = 'EDIT_SONG_SUCCESS'
export const EDIT_SONG_FAIL = 'EDIT_SONG_FAIL'

export const DELETE_SONG_REQUEST = 'DELETE_SONG_REQUEST'
export const DELETE_SONG_SUCCESS = 'DELETE_SONG_SUCCESS'
export const DELETE_SONG_FAIL = 'DELETE_SONG_FAIL'

export const DELETE_SONG_RESET = 'DELETE_SONG_RESET'
export const UPDATE_SONG_RESET = 'UPDATE_SONG_RESET'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'
